<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\Ticketing\Ticketing.Api\Ticketing.Api.csproj" />
    <ProjectReference Include="..\..\src\Services\Reporting\Reporting.Api\Reporting.Api.csproj" Aliases="reporting" />
    <ProjectReference Include="..\..\src\Services\EventCatalog\EventCatalog.Api\EventCatalog.Api.csproj" Aliases="catalog" />
    <ProjectReference Include="..\..\src\Services\Notifications\Notifications.Worker\Notifications.Worker.csproj" Aliases="notifications" />
  </ItemGroup>
</Project>
